- name: Virutal Machine - Snapshot, Shutdown, Upgrade Hardware, verify, Power on
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create a sub folder under VM folder on given datacenter
      community.vmware.vcenter_folder:
        hostname: 172.16.10.44
        username: administrator@vsphere.local
        password: Roma2016**
        datacenter: DemoDC
        folder_name: WazuhServer
        state: present
        validate_certs: no
      delegate_to: localhost
      
    - name: Gather all registered virtual machines
      community.vmware.vmware_deploy_ovf:
        hostname: 172.16.10.44
        username: administrator@vsphere.local
        password: Roma2016**
        datacenter: DemoDC
        cluster: DemoCS
        datastore: Data
        name: WazuhSRV
        folder: DemoDC/vm/WazuhServer
        validate_certs: no
        power_on: yes
        ovf: /var/lib/awx/template.ova
      delegate_to: localhost
    
    - pause: seconds=120

    - name: Change ip address of guest machine
      community.vmware.vmware_vm_shell:
        hostname: 172.16.10.44
        username: administrator@vsphere.local
        password: Roma2016**
        validate_certs: no
        datacenter: DemoDC
        folder: DemoDC/vm/WazuhServer
        vm_id: WazuhSRV
        vm_username: root
        vm_password: Roma2016**
        vm_shell: "/usr/bin/nmcli"
        vm_shell_args: "connection modify ens160 IPv4.address 172.16.10.41"
      delegate_to: localhost
     
    - name: Change gw of guest machine
      community.vmware.vmware_vm_shell:
        hostname: 172.16.10.44
        username: administrator@vsphere.local
        password: Roma2016**
        validate_certs: no
        datacenter: DemoDC
        folder: DemoDC/vm/WazuhServer
        vm_id: WazuhSRV
        vm_username: root
        vm_password: Roma2016**
        vm_shell: "/usr/bin/nmcli"
        vm_shell_args: "connection modify ens160 IPv4.gateway 172.16.10.1"
      delegate_to: localhost

    - name: Change dns s of guest machine
      community.vmware.vmware_vm_shell:
        hostname: 172.16.10.44
        username: administrator@vsphere.local
        password: Roma2016**
        validate_certs: no
        datacenter: DemoDC
        folder: DemoDC/vm/WazuhServer
        vm_id: WazuhSRV
        vm_username: root
        vm_password: Roma2016**
        vm_shell: "/usr/bin/nmcli"
        vm_shell_args: "connection modify ens160 IPv4.dns 8.8.8.8"
      delegate_to: localhost
      
    - name: restart_services
      community.vmware.vmware_vm_shell:
        hostname: 172.16.10.44
        username: administrator@vsphere.local
        password: Roma2016**
        validate_certs: no
        datacenter: DemoDC
        folder: DemoDC/vm/WazuhServer
        vm_id: WazuhSRV
        vm_username: root
        vm_password: Roma2016**
        vm_shell: "/usr/bin/nmcli"
        vm_shell_args: "networking off && nmcli networking on"
      delegate_to: localhost      
  
    - pause: seconds=10
     
    - name: Wazuh_Kurulumu
      community.vmware.vmware_vm_shell:
        hostname: 172.16.10.44
        username: administrator@vsphere.local
        password: Roma2016**
        validate_certs: no
        datacenter: DemoDC
        folder: DemoDC/vm/WazuhServer
        vm_id: WazuhSRV
        vm_username: root
        vm_password: Roma2016**
        vm_shell: "/usr/bin/curl"
        vm_shell_args: "-so ~/unattended-installation.sh https://raw.githubusercontent.com/wazuh/wazuh-documentation/4.1/resources/open-distro/unattended-installation/unattended-installation.sh && bash ~/unattended-installation.sh > /root/keys.txt"
      delegate_to: localhost 

    - pause: seconds=10
    
    - name: Password_Create
      community.vmware.vmware_vm_shell:
        hostname: 172.16.10.44
        username: administrator@vsphere.local
        password: Roma2016**
        validate_certs: no
        datacenter: DemoDC
        folder: DemoDC/vm/WazuhServer
        vm_id: WazuhSRV
        vm_username: root
        vm_password: Roma2016**
        vm_shell: "/usr/bin/cat"
        vm_shell_args: "/root/keys.txt | grep "The password" > /root/password.txt"
      delegate_to: localhost 
