- name: Virutal Machine - Snapshot, Shutdown, Upgrade Hardware, verify, Power on
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Gather all registered virtual machines
      community.vmware.vmware_vm_info:
        hostname: 172.16.10.44
        username: administrator@vsphere.local
        password: Roma2016**
        vm_type: vm
        validate_certs: no
      delegate_to: localhost
      register: vminfo

    - debug:
        var: vminfo
